name: Changelog

on:
  workflow_run:
    workflows: ['Tag']
    types:
      - completed

jobs:
  create-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1.3.0
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          # exclude_types: other,doc,chore

      - name: Extract tag name
        id: extract_tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          else
            echo "This is not a tag ref: ${GITHUB_REF}"
            exit 1
          fi

      - name: Create release
        if: env.TAG_NAME
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: ${{ steps.changelog.outputs.changes }}
