name: Changelog

on:
  workflow_run:
    workflows: ['Tag']
    types:
      - completed
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.TOKEN_GITHUB }} 