name: Create Tag

on:
  push:
    branches:
      - "main"


jobs:
  create_tag_and_generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v2.2.0
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          package-path: ./package.json