name: Create Tag

on:
  push:
    branches:
      - "main"

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Tag
        uses: jaywcjlove/create-tag-action@v2.2.0
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          package-path: ./package.json
