name: Create Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      # Passaggi per creare il tag
      - name: Checkout code
        uses: actions/checkout@v2

  generate_changelog:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - name: Generate changelog
        uses: jaywcjlove/changelog-generator@v2.1.0
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          # filter-author: '(jaywcjlove|dependabot)'
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
