name: Create Tag

on:
  push:
    branches:
      - "main"
    paths-ignore:
    - '.github/**/*.yml'
    - '.gitignore'

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Create Tag
        uses: jaywcjlove/create-tag-action@v2.2.0
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          package-path: ./package.json
